# Generated by Django 6.0.3 on 2026-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('under_18', 'Below 18'), ('18_22', '18–22'), ('23_30', '23–30'), ('over_30', '30+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(blank=True, choices=[('science_eng', 'Science / Engineering'), ('arts_humanities', 'Arts / Humanities'), ('commerce_finance', 'Commerce / Finance'), ('medical_bio', 'Medical / Biology'), ('other', 'Other / Not sure')], max_length=20, null=True),
        ),
    ]
