# Generated by Django 6.0.3 on 2026-03-14 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='daily_hours',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='daily_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='goal_type',
            field=models.CharField(choices=[('clarity', 'Conceptual Clarity'), ('exam', 'Exam Preparation'), ('revision', 'Quick Revision')], default='clarity', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='target_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='AIPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('trigger_reason', models.CharField(choices=[('initial', 'Initial Generation'), ('missed_days', 'Missed Days Catch-up'), ('low_performance', 'Low Performance Adjustment'), ('user_request', 'User Requested Change')], default='initial', max_length=20)),
                ('ai_model', models.CharField(default='nvidia/nemotron-3-nano-30b-a3b:free', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='study_plan.studyplan')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AITopicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('allocated_minutes', models.PositiveIntegerField()),
                ('sequence_order', models.PositiveIntegerField()),
                ('ai_reasoning', models.JSONField(blank=True, null=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_plans', to='study_plan.aiplanversion')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('available_minutes', models.PositiveIntegerField()),
                ('actual_minutes_spent', models.PositiveIntegerField(default=0)),
                ('session_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='study_plan.aiplanversion')),
                ('topic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='study_plan.aitopicplan')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('concept', 'Concept Explanation'), ('example', 'Practical Example'), ('practice', 'Practice Exercise'), ('revision', 'Revision Note')], max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('task_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_plan.studysession')),
            ],
            options={
                'ordering': ['task_order'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understanding_level', models.CharField(choices=[('clear', 'Clear'), ('partial', 'Partial Understanding'), ('not_clear', 'Not Clear')], max_length=20)),
                ('time_spent_minutes', models.PositiveIntegerField()),
                ('user_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='study_plan.sessiontask')),
            ],
        ),
    ]
