# Generated by Django 6.0.3 on 2026-03-14 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_remove_studyplan_daily_hours_studyplan_daily_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
