# Generated by Django 6.0.3 on 2026-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0003_alter_studyplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
