# Generated by Django 6.0.3 on 2026-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0004_studysession_unlocked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='current_level',
            field=models.CharField(choices=[('beginner', 'Beginner (Starting from zero)'), ('intermediate', 'Intermediate (Know basics)'), ('advanced', 'Advanced (Deep understanding)')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='goal_type',
            field=models.CharField(choices=[('job', 'Job (Interviews, Practical skills)'), ('exam', 'Exam Preparation (Theory, Syllabus)'), ('career_switch', 'Career Switch (Extra basics)'), ('skill_upgrade', 'Skill Upgrade (More depth)'), ('curiosity', 'Curiosity (Exploratory)'), ('clarity', 'Conceptual Clarity')], default='job', max_length=20),
        ),
    ]
