# Generated by Django 6.0.3 on 2026-03-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0005_studyplan_current_level_alter_studyplan_goal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='session_task',
        ),
        migrations.RenameField(
            model_name='studyplan',
            old_name='target_days',
            new_name='total_days',
        ),
        migrations.AddField(
            model_name='aitopicplan',
            name='allocated_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aitopicplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField()),
                ('allocated_minutes', models.PositiveIntegerField(default=20)),
                ('ai_generated_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sessions', to='study_plan.studysession')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='SessionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_md', models.TextField()),
                ('ai_model', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='study_plan.subsession')),
            ],
        ),
        migrations.DeleteModel(
            name='SessionTask',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
