# Generated by Django 6.0.3 on 2026-03-16 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('study_plan', '0006_remove_userfeedback_session_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='selected_answers',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answers',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='sub_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='study_plan.subsession'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_md', models.TextField()),
                ('ai_model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='quiz.quizattempt')),
            ],
        ),
    ]
