# Generated by Django 6.0.3 on 2026-03-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('quiz', '0002_remove_quizattempt_selected_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
